Adding included areas and illing the content of the pages
7malevich/dec pull request #5
Opened 2024-03-12 15:00 UTC by Dmitriy-Faley

2024-03-13 07:20 UTC, Ziuziun-Pavel requested changes

2024-03-13 07:20 UTC, Ziuziun-Pavel commented on local/templates/main/header.php
а зачем ты закомментил выбор региона?

2024-03-13 07:20 UTC, Ziuziun-Pavel commented on local/templates/.default/components/bitrix/main.include/inc_korporativnym_klientam_organizatsiya_planovye_i_vneplanovye_proverki_raschetnykh_priborov/template.php
если где-то есть вёрстка не выноси ее в отдельную включаемую область. Добавляй включаемые области только на страницах где чисто текст либо нет контента. Возможно в будущем это придется разносить по ИБ

2024-03-13 07:34 UTC, Dmitriy-Faley commented on local/templates/main/header.php
У меня на локалке была ошибка из-за него, что бы не тратить время на исправление, закоментил

2024-03-13 07:35 UTC, Dmitriy-Faley commented on local/templates/.default/components/bitrix/main.include/inc_korporativnym_klientam_organizatsiya_planovye_i_vneplanovye_proverki_raschetnykh_priborov/template.php
ок, понял

2024-03-14 06:28 UTC, Ziuziun-Pavel requested changes
Доделывай остальные страницы и делай повторный  запрос на ревью

2024-03-14 11:11 UTC, Ziuziun-Pavel approved these changes

2024-03-14 11:11 UTC, merged